name: Compile bunch1s fortran module

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11.2
      uses: actions/setup-python@v3
      with:
        python-version: '3.11.2'
    
    - name: Install Deps
      run: pip install -r requirements.txt
    
    - uses: awvwgk/setup-fortran@main
      id: setup-fortran
      with:
        compiler: gcc
        version: 12
    
    - name: Get latest CMake
      uses: lukka/get-cmake@latest

    - name: build
      run: mkdir build_unix && cmake -S . -B ./build_unix && cd build_unix && make
      
    - uses: actions/upload-artifact@v3
      with:
        name: build_unix
        path: build_unix/bunch1s.*

  build-windows:
    runs-on: windows-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    
    - uses: awvwgk/setup-fortran@main
      id: setup-fortran
      with:
        compiler: gcc
        version: 12
    
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.13
    
    - name: Set up Python 3.11.2
      uses: actions/setup-python@v3
      with:
        python-version: '3.11.2'
    
    - name: Install Deps
      run: python -m pip install -r requirements.txt
      
    - name: Print numpy headers
      run: python -c "import numpy.f2py; print(numpy.f2py.get_include())"
    
    - name: build
      run: $python_exec = python -c "import sys; print(sys.executable)"; mkdir build_windows; cmake -DPYTHON_EXECUTABLE=$python_exec -S . -B ./build_windows -G "Unix Makefiles"; cd build_windows ; make 
    
    - uses: actions/upload-artifact@v3
      with:
        name: build_windows
        path: build_windows/bunch1s.*
