name: Compile bunch1s fortran module

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    
    - name: Install Deps
      run: pip install -r requirements.txt
    
    - uses: awvwgk/setup-fortran@main
      id: setup-fortran
      with:
        compiler: gcc
        version: 12
    
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.13

    - name: build
      run: mkdir build && cmake -S . -B ./build && cd build && make
      
    - uses: actions/upload-artifact@v3
      with:
        name: build_unix
        path: build/bunch1s.*

  build-windows:
    runs-on: windows-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    # # windows runners come with a version pre-installed
    # - name: Set up Python 3.10
    #   uses: actions/setup-python@v3
    #   with:
    #     python-version: '3.10'
        
    - uses: awvwgk/setup-fortran@main
      id: setup-fortran
      with:
        compiler: gcc
        version: 12
    
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.13

    - name: Install Deps
      run: python3 -m pip install -r requirements.txt
      
    - name: Print numpy headers
      run: python3 -c "import numpy.f2py; print(numpy.f2py.get_include())"
    
    - name: build
      run: $python_exec = python3 -c "import sys; print(sys.executable)"; mkdir build_windows; cmake -DPYTHON_EXECUTABLE=$python_exec -S . -B ./build_windows -G "Unix Makefiles"; cd build_windows ; make 
      
    - uses: actions/upload-artifact@v3
      with:
        name: build_windows
        path: build_windows/bunch1s.*
